sudo: required
language: bash
addons:
  ssh_known_hosts: jonathanadamski.com
  apt:
    packages:
    - docker-ce

jobs:
  include:
    - stage: build/push ui
      on:
        branch: feature/travis
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/wedding-ui wedding-ui
      - docker tag $DOCKER_USERNAME/wedding-ui $DOCKER_USERNAME/wedding-ui:$(date +%Y-%m-%d)
      - docker push $DOCKER_USERNAME/wedding-ui

    - stage: buil/push api
      on:
        branch: feature/travis
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t $DOCKER_USERNAME/wedding-api wedding-api
      - docker tag $DOCKER_USERNAME/wedding-api $DOCKER_USERNAME/wedding-api:$(date +%Y-%m-%d)
      - docker push $DOCKER_USERNAME/wedding-api

    - stage: update host
      on:
        branch: feature/travis
      script:
      - openssl aes-256-cbc -K $encrypted_38ced7ab948c_key -iv $encrypted_38ced7ab948c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
      - eval "$(ssh-agent -s)"
      - chmod 600 /tmp/deploy_rsa
      - ssh-add /tmp/deploy_rsa
      - ssh -i /tmp/deploy_rsa ubuntu@jonathanadamski.com "sudo systemctl service jna-wedding restart"
