sudo: required
language: node_js
addons:
  ssh_known_hosts: jonathanadamski.com
  apt:
    packages:
    - docker-ce
before_install:
- openssl aes-256-cbc -K $encrypted_38ced7ab948c_key -iv $encrypted_38ced7ab948c_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
script:
  provider: script
  script: bash _scripts/build
  on:
    branch: master
deploy:
  provider: script
  script: bash _scripts/push-to-docker
  on:
    branch: master
after_deploy:
  provider: script
  script: bash _scripts/push-to-host
  on:
    branch: master
