version: '3'

services:
  db:
    image: postgres:10.4
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
  api:
    image: adamski52/wedding-api
    env_file:
      - .env
    ports:
      - "9090:9090"
    networks:
      - backend
  ui:
    image: adamski52/wedding-ui
    ports:
      - "9000:9000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
