version: '3'

services:
  db:
    image: wedding-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    image: wedding-api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "9090:9090"
  ui:
    image: wedding-ui
    ports:
      - "9000:9000"
