#!/bin/bash

# use me locally to generate a key for travis to use to connect to host
# its going to cram some stuff into before_install.  we only need to keep the hashed filename part.

# e.g.:
# - openssl aes-256-cbc -K $encrypted_SOMETHING_key -iv $encrypted_SOMETHING_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
# - eval "$(ssh-agent -s)"
# - chmod 600 /tmp/deploy_rsa
# - ssh-add /tmp/deploy_rsa

ssh-keygen -t rsa -b 4096 -C 'me@jonathanadamski.com' -f ./deploy_rsa
travis encrypt-file deploy_rsa --add

# cram the new ID into host, using existing key
cat deploy_rsa | ssh -i ~/.ssh/jna*.pem ubuntu@jonathanadamski.com "sudo tee -a /.ssh/authorized_keys"

rm -f deploy_rsa deploy_rsa.pub
