#!/bin/bash

# use me to push latest github content (as a docker build) to docker hub.

DATE=`date +%Y-%m-%d`

docker tag wedding-api adamski52/wedding-api
docker tag wedding-api adamski52/wedding-api:$DATE

docker tag wedding-ui adamski52/wedding-ui
docker tag wedding-ui adamski52/wedding-ui:$DATE

docker push adamski52/wedding-api
docker push adamski52/wedding-ui
